---

- name: Set virtual memory limit
  sysctl:
    name: vm.max_map_count
    value: '262144'

- name: create ELK docker structure on server in /home/docker/elk
  file:
    name: /home/docker/elk/patterns
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install elk docker-compose
  template:
    src: docker-compose.yaml.j2
    dest: /home/docker/elk/docker-compose.yml
    owner: root
    group: root
    mode: '0400'
  notify:
    - start elk docker

- name: Push logstash certificate
  copy:
    content: "{{ logstash_tls_crt }}"
    dest: "/home/docker/elk/logstash.crt"
    owner: '1000'
    group: '1000'
    mode: '0644'
  notify:
    - start elk docker

- name: Push logstash certificate private key
  copy:
    content: "{{ logstash_tls_key }}"
    dest: "/home/docker/elk/logstash.key"
    owner: '1000'
    group: '1000'
    mode: '0600'
  notify:
    - start elk docker

- name: Copy logstash configuration file
  template:
    src: logstash.conf.j2
    dest: /home/docker/elk/logstash.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - start elk docker

- name: Copy odoo patterns for logstash
  copy:
    src: odoo-pattern
    dest: /home/docker/elk/patterns/odoo
    owner: root
    group: root
    mode: '0644'
  notify:
    - start elk docker
